# Serviços / Contêiners
services:

  # Contêiner do Backend
  web_backend:
    container_name: gestao-pecuaria-web_backend
    build: 
      context: .
      dockerfile: ./back_gestao-pecuaria/Dockerfile.backend
    networks:
      - rede_pecuaria
    ports:
      - "8000:8000"
    volumes:
      - ./back_gestao-pecuaria/Projeto_Pesquisa_e_Gestão_Pecuaria:/back_gestao-pecuaria/Projeto_Pesquisa_e_Gestão_Pecuaria
      - ./back_gestao-pecuaria/data/web/static:/back_gestao-pecuaria/data/web/static
      - ./back_gestao-pecuaria/data/web/media:/back_gestao-pecuaria/data/web/media
    env_file:
      - ./back_gestao-pecuaria/.env
    depends_on:
      - psql
    user: "1000:1000" 
    command: ["sh", "-c", "/scripts/commands.sh"]
    # command: ["sh", "-c", "pwd"]
  # Container do Frontend
  web_frontend:
    container_name: gestao-pecuaria-web_frontend
    build: 
      context: .
      dockerfile: ./front_gestao-pecuaria/Dockerfile.frontend

    networks:
      - rede_pecuaria
    ports:
      - "8080:8080"
    volumes:
      - ./front_gestao-pecuaria/frontend:/front_gestao-pecuaria/frontend
    env_file:
      - ./front_gestao-pecuaria/frontend/.env
    depends_on:
      - psql
      - web_backend
    command: ["yarn", "dev"]

  # Contêiner do Banco de Dados
  psql:
    container_name: psql
    image: postgres:13-alpine
    networks:
      - rede_pecuaria
    volumes:
      - ./back_gestao-pecuaria/data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./back_gestao-pecuaria/.env
    ports:
      - "5432:5432"

# Rede de comunicação entre os contêiners.
networks:
  rede_pecuaria:
    driver: "bridge"

